name: Rust

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update Toolchain
      run: |
        rustup self update
        rustup update
    - name: Lint
      run: |
        rustup component add clippy
        cargo clippy --all-targets --all-features -- -D warnings
        cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
